language: go
go:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - tip
install:
  - go get github.com/StefanSchroeder/Golang-Ellipsoid/ellipsoid
matrix:
  allow_failures:
    - go: 1.3
    - go: 1.4
    - go: tip

notifications:
  email: false
    slack:
    if: branch in (main, staging, production)
    on_success: never
    on_failure: always
    on_pull_requests: false
    secure: DBwbG4zeFLtgPrNlXTS2RlPGITVMKQsDRJyopsj/bRB034eStRMT4ynG/5IbZp8BmRTB7TlYGxBF6YPZo27yKpFtL9LzlK5SnyzhZRwYqFHh2illTdT+VS6BdPm0rXO6rgVbZABzmHcpOz0RZsaUGd5mEcgPu/YmAEvg/dgvPnpH9oRuKa6hMTMI3MGLgIzaQveGMY8jt3s3GBWkzSdbxYF9bUjzdiu52HtsewiRWruNUXbkPnupnawOQ17RFJZSjJNe7N+lLr6XcYYD7vgxB6v4u6mHz/hJOpc/cftImNIIjvpIjUbtfU+dshBixIbkary3iPJo4I0Svw8WopJiEY0KQkLJHV12I1QYIgk1eBdbEpH90PDOBocEKD/zekHA1cMCUYF/tJT/LeOJ/tqv668BoBpB+vCEpUvfsTEW4qLxQk3+GmQqQWWVdywGQpGU+P7+uDvFntcjoiZJcfXAe314pa6zWVFVDhWVvUFXhpOl2DTfeJrUf5p62udQSlJwMa/rif4LLbRM4mjaWOQUJ/GPKm6MZNneVgsxus0ku9IP7ZOjd3x5ETDt8DoNsPPC/v9SJ901kvYiMW2Uh6dUg7viZFvI9IILVqWnJ+t3WWOEIW8Vmcw1jY8s9EpnfUFLWlSF4Hid7Fjq+GxsWdrJ3Zu/rtLGOJpfBPnZoQmup98=
